# Generated by Django 2.2.4 on 2019-08-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190819_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', '-publish_date', '-updated', '-timestamp']},
        ),
    ]
